server:
  port: 8080
spring:
  application:
    name: "authentication-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
logging:
  level:
    co.com.pragma: trace
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
      base-path: /auth/actuator
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "auth"
    schema: "public"
    username: "admin"
    password: "admin"
    ssl: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

springdoc:
  swagger-ui:
    path: /auth/swagger-ui.html
  api-docs:
    path: /auth/v3/api-docs